services:
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    restart: unless-stopped
    ports:
      - "13378:80"
    volumes:
      - /opt/hemmaos/data/audiobookshelf/config:/config
      - /opt/hemmaos/data/audiobookshelf/metadata:/metadata
      - /opt/hemmaos/data/media/audiobooks:/audiobooks
      - /opt/hemmaos/data/media/podcasts:/podcasts
    networks:
      - hemmaos

networks:
  hemmaos:
    external: true
