services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    ports:
      - "8096:8096"
    volumes:
      - /opt/hemmaos/data/jellyfin/config:/config
      - /opt/hemmaos/data/jellyfin/cache:/cache
      - /opt/hemmaos/data/media:/media:ro
    environment:
      - JELLYFIN_PublishedServerUrl=${TAILSCALE_DOMAIN:-localhost}
    networks:
      - hemmaos

networks:
  hemmaos:
    external: true
