services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    ports:
      - "8096:8096"
    volumes:
      - /opt/home-os/data/jellyfin/config:/config
      - /opt/home-os/data/jellyfin/cache:/cache
      - /opt/home-os/data/media:/media:ro
    environment:
      - JELLYFIN_PublishedServerUrl=${TAILSCALE_DOMAIN:-localhost}
    networks:
      - home-os

networks:
  home-os:
    external: true
