services:
  transmission:
    container_name: transmission
    image: lscr.io/linuxserver/transmission:latest
    restart: unless-stopped
    ports:
      - "9091:9091"
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Europe/Stockholm
    volumes:
      - /opt/hemmaos/data/transmission/config:/config
      - /opt/hemmaos/data/media/downloads:/downloads
    networks:
      - hemmaos

networks:
  hemmaos:
    external: true
